### ISSUE TITLE
 Inflate.min.js error 这个错误是如何解决的？

### ISSUE THREAD

**Issue by snoopy1412** [xiongtongzi/import-three-examples#2]
![image](https://user-images.githubusercontent.com/13896109/51099838-fbd20f80-180d-11e9-8c74-75c05a116876.png)

如何解决这个的报错？

**Comment by xiongtongzi** [comment]
下载最新的 import-three-examples@2.1.5 版本
这个问题已经解决。。

**Comment by snoopy1412** [comment]
> 下载最新的 import-three-examples@2.1.5 版本
> 这个问题已经解决。。

nice

**Comment by xiongtongzi** [comment]
如果还有人需要模块化开发threeJs 麻烦帮推荐一下这个插件！ 感谢 😄

**Comment by snoopy1412** [comment]
> 如果还有人需要模块化开发threeJs 麻烦帮推荐一下这个插件！ 感谢 😄

很好用，坐等更多features
