### ISSUE TITLE
some thing wrong

### ISSUE THREAD

**Issue by john-keith** [xiongtongzi/import-three-examples#3]
I heard that your qq was blocked, hahahahahahahaha, come to me, your new qq, I pull you

**Comment by xiongtongzi** [comment]
明天解封，没事

**Comment by john-keith** [comment]
Ooo, that's good

**Comment by kuangyazhou** [comment]
什么鬼？？？黄图封七天

**Comment by xiongtongzi** [comment]
![image](https://user-images.githubusercontent.com/19956089/58943963-67b01700-87b3-11e9-94a2-9940923e0150.png)
Because it was discussed

**Comment by john-keith** [comment]
why this picture cause your qq blocked, Is that you are too sao？

**Comment by xiongtongzi** [comment]
you open VPN，Search for （six four）

**Comment by john-keith** [comment]
ok i know, tank is related to six-four

**Comment by kuangyazhou** [comment]
I'm just a tourist whatever happens here has nothing to do with me

**Comment by john-keith** [comment]
github is not belong to china zf, dont be affrid

**Comment by xiongtongzi** [comment]
And we speak English without keywords

**Comment by john-keith** [comment]
yes you are right
