### ISSUE TITLE
内部文件找不到对应的引用名

### ISSUE THREAD

**Issue by lettywiterock** [xiongtongzi/import-three-examples#4]
vue.runtime.esm.js?2b0e:619 [Vue warn]: Failed to resolve async component: function ThreeView() {
      return Promise.all(/*! import() */[__webpack_require__.e(7), __webpack_require__.e(3)]).then(__webpack_require__.bind(null, /*! _c/threeGeometry */ "./src/components/threeGeometry/index.js"));
    }
Reason: ReferenceError: TWEEN is not defined

因该是引用THREE导致的，因为THREE没有做ES6的npm，所以使用本项目，但是对应的第三方库类，就找不到了有没有详细一些的randme

**Comment by lettywiterock** [comment]
比如
new THREE.SphereBufferGeometry()；
new Scene();
new THREE.WebGLRenderer();
等等

**Comment by xiongtongzi** [comment]
你列的这三个方法都内置在THREE，而不是外部库
场景在THREE内置new THREE.Scene()
```
import * as THREE from 'three'
new THREE.SphereBufferGeometry()；
new THREE.Scene();
new THREE.WebGLRenderer();
```

**Comment by xiongtongzi** [comment]
ok了咩   我这个库是为了帮助模块化引入examples里面的外部库噢
