### ISSUE TITLE
threejs自带这些

### ISSUE THREAD

**Issue by ManaZero37** [xiongtongzi/import-three-examples#5]
[https://threejs.org/docs/index.html#manual/en/introduction/Import-via-modules](url)

**Comment by xiongtongzi** [comment]
threeJs中的确自带这些库，但three中的这些库没办法直接模块化引入，我只是方便了在webpack的架构中更简易的引入这些库

**Comment by xiongtongzi** [comment]
你可能有点误解，你给的文档路径是docs。而我是帮助引入examples路径下的库

**Comment by ManaZero37** [comment]
> 你可能有点误解，你给的文档路径是docs。而我是帮助引入examples路径下的库

可能你没有仔细看文档，比如引用控制器，文档中的引用方法
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
你的引用方法
import OrbitControls from "three/examples/js/controls/OrbitControls"

**Comment by xiongtongzi** [comment]
threeJs 在今年年初更新了jsm目录 。对于他已经有的库你可以直接使用他的，但是直到现在他也没有全部模块化完成噢，如果他还没模块户的库你可以尝试我的插件

**Comment by ManaZero37** [comment]
> threeJs 在今年年初更新了jsm目录 。对于他已经有的库你可以直接使用他的，但是直到现在他也没有全部模块化完成噢，如果他还没模块户的库你可以尝试我的插件

原来是这样啊，我也是在用vue中弄threejs，刚刚开始弄以为它全弄完了呢，所以过来提醒下。

**Comment by xiongtongzi** [comment]
刚刚看了下 现在好像还挺全的

**Comment by ManaZero37** [comment]
> 刚刚看了下 现在好像还挺全的

目前我用到的刚刚看了下都有，也可能我用的还比较少

**Comment by xiongtongzi** [comment]
因为我当时写这个的时候大概是@0.99 ，还没有jsm目录。现在有更好的解决方案当然更好了
