### ISSUE TITLE
大佬能解释下官方的jsm文件是怎么回事吗？你说的更好的模块化开发解决方案是啥意思？

### ISSUE THREAD

**Issue by dg489** [xiongtongzi/import-three-examples#6]

**Comment by xiongtongzi** [comment]
作者年初开始手动将原本不能模块化引入的文件改成可以模块化引入的文件
新版three的npm包中自带jsm目录
例如: OrbitControls
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
以后就可以直接去three的jsm目录去找插件了。已经可以直接引入了，无需再做其他处理
jsm目录的git链接在我项目说明的最下方

**Comment by dg489** [comment]
谢谢大佬，我用fbx加载一直加载不成功，报Cannot find the version number for the file given.百度说是路径问题，但是我是放在components目录下，跟.vue是同一个目录，是不是webpack还需要特别配置

**Comment by xiongtongzi** [comment]
fbxLoader的话 还需要引入一个压缩的js包。这个问题我已经解决了

**Comment by xiongtongzi** [comment]
Duplicate of #2

**Comment by xiongtongzi** [comment]
这个错的话，我要看看。。。

**Comment by dg489** [comment]
好的，我是直接把官方demo改成vue，然后卡在了fbxload这，一直导入不成功，也不是报你上面issues的错，因为我是根据你说的直接引入了jsm里的Load

**Comment by xiongtongzi** [comment]
你的项目现在方便发我一份吗   因为我这边刚刚尝试了一下，没出现你的这个报错。 qq:932230508
